shell.run("wget https://raw.githubusercontent.com/Wilma456/Computercraft/master/Owncloud/Cloud/owncloud.lua /owncloud/owncloud")
shell.run("wget https://raw.githubusercontent.com/Wilma456/Computercraft/master/Owncloud/Cloud/plugins/file.lua /owncloud/plugins/file")
shell.run("wget https://raw.githubusercontent.com/Wilma456/Computercraft/master/Owncloud/Cloud/manual.txt /owncloud/manual")
file = fs.open("/owncloud/user/root","w")
file.write("root")
file.close()
fi = fs.open ("/owncloud/config/channel","w")
fi.write("2100")
fi.close()
print("Thank you for install Owncloud. To start Owncloud, run owncloud/owncloud. To read the manual run edit /owncloud/manual")
